#!/bin/bash

test "${ACTION}" = "add" || exit 0
echo "${DEVNAME}" | grep -E "^/dev/input/event[0-9]+$" || exit 0

nohup evsieve --input "${DEVNAME}" persist=exit --map rel:wheel rel:x --output name="Egret-II Mini Paddle" >/dev/null 2>"/var/log/virtual-e2m-paddle-trackball-devices.log" &


