#!/bin/bash

ACTION=$1
PARAM=$2
INTERNALCARD=$(cat /boot/boot/batocera.board)

if test "${ACTION}" = "setOutput"
then
        # force no hdmi if it is unplugged
        HDMISTATUS=$(cat /sys/devices/virtual/switch/hdmi/state)

        if test "${HDMISTATUS}" = 0
        then
            batocera-settings-set display.rotate 1
            curl http://localhost:1234/quit # No confirmation when unplugging HDMI 
            # force 0 which is supposed to be the internal device
	    amixer -c 1 cset name='Speaker Function' 1
	    echo 0 > /sys/class/disp/disp/attr/lcd_para 
	    echo 1 > /sys/class/lcd/reload_lcd_panel_func 
	    echo 0 > /sys/class/disp/disp/attr/lcd 
	    if test "${INTERNALCARD}" = "e2m"
	    then
	        # EGRET II Mini
	        fbset -g 768 1024 768 2048 32
	    
	    else
	        # Astro City Mini
	        fbset -g 480 800 480 1600 32
	    fi
	    echo 1 > /sys/class/disp/disp/attr/lcd
        else
	        batocera-settings-set display.rotate 0
            	curl http://localhost:1234/quit
		#?confirm=switchscreen
		amixer -c 1 cset name='Speaker Function' 0
		echo 1 > /sys/class/disp/disp/attr/lcd_para 
		echo 1 > /sys/class/lcd/reload_lcd_panel_func 
		echo 0 > /sys/class/disp/disp/attr/lcd
		# HDMI output set to 720p
		fbset -g 1280 720 1280 1440 32 
		echo 1 > /sys/class/disp/disp/attr/lcd
        fi
fi

